language: rust
rust:
    - stable
    - beta
    - nightly

os:
    - linux

matrix:
    allow_failures:
        - rust: nightly

addons:
    apt:
        packages:
            - freeglut3-dev
            - libxxf86vm-dev
            - libosmesa6-dev
