language: rust
rust:
    - stable
    - beta
    - nightly

os:
    - linux
    - osx

matrix:
    allow_failures:
        - rust: nightly

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install freetype ; fi
